# Generated by Django 5.2.6 on 2025-09-11 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(default='Hyderabad', max_length=120)),
                ('category_name', models.CharField(default='General', max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['school__order', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='leadershipgroup',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['department__order', 'order', 'name']},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='summary',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='title',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='summary',
            new_name='accreditation',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='summary',
            new_name='about',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='leader',
            unique_together={('group', 'name')},
        ),
        migrations.RemoveField(
            model_name='leadershipgroup',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'name')},
        ),
        migrations.RemoveField(
            model_name='school',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='school',
            name='tagline',
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leadershipgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadershipgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='fees',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='program',
            name='outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='specializations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='leadershipgroup',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.RemoveField(
            model_name='leader',
            name='order',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='program',
            name='mode',
        ),
    ]
