# Generated by Django 5.0.6 on 2025-09-11 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_jobposting_delete_job_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('school', 'order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ('-is_active', 'order', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ('group', 'order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='leadershipgroup',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('department', 'order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('order', 'name')},
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='photo_url',
            new_name='image_url',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leader',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leader',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadershipgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='category_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='details',
            field=models.TextField(blank=True, default=[], help_text='One bullet per line.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='leader',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='cms.leadershipgroup'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='leader',
            name='role',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='leadershipgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='leadershipgroup',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='specializations',
            field=models.TextField(blank=True, default=[], help_text='Comma-separated list (e.g., Neuro, Ortho, ...)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'slug')},
        ),
        migrations.RemoveField(
            model_name='leader',
            name='bio',
        ),
    ]
