# Generated by Django 5.0.6 on 2025-09-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_department_options_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='show_profile_button',
            field=models.BooleanField(default=True, help_text="Enable/disable the 'View Profile' button on leadership cards"),
        ),
    ]
