# Generated by Django 5.0.6 on 2025-09-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_leader_show_profile_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='show_profile_button',
        ),
    ]
