# Generated by Django 5.0.6 on 2025-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_leader_show_profile_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='image_url',
        ),
        migrations.AddField(
            model_name='leader',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='leadership/'),
        ),
    ]
