# Generated by Django 5.0.6 on 2025-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_leader_image_url_leader_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='leader',
            name='experience',
            field=models.TextField(blank=True, help_text='Professional experience and achievements'),
        ),
        migrations.AddField(
            model_name='leader',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='leader',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Educational qualifications and certifications'),
        ),
        migrations.AddField(
            model_name='leader',
            name='viewProfileEnabled',
            field=models.BooleanField(default=True, help_text="Show 'View Profile' button on frontend"),
        ),
    ]
