# Generated by Django 5.2.5 on 2025-08-12 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('sort_order', 'title')},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('sort_order', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ('name',), 'verbose_name': 'Job category', 'verbose_name_plural': 'Job categories'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='position',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='label',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='short_description',
        ),
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/cv/'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'In review'), ('closed', 'Closed')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='benefit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='benefit',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='benefit',
            name='title',
            field=models.CharField(default='Untitled Benfits', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
